version: "3.7"

x-app-volumes: &app-volumes
  - .:/app:cached
  - ~/.bash_history:/root/.bash_history
  - bundle_cache:/bundle_cache

services:
  app:
    build: .
    volumes: *app-volumes
    environment:
      - PORT=8000
      - BUNDLE_PATH=/bundle_cache
    command: bash -c "bundle exec ruby src/server.rb"
    ports:
      - "8000:8000"

  infra:
    build:
      context: ./infra
      dockerfile: Dockerfile
    volumes:
      - ./infra:/infra
      - ~/.kube/config:/root/.kube/config
    environment:
      - GITHUB_REGISTRY_CREDS
      - INGRESS_HOST

volumes:
  bundle_cache:
