apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dte
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.service.name }}
                port:
                  number: {{ .Values.port }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.host }}
